import { AlertTriangle } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="flex items-center gap-2 px-4 py-2 bg-warning/10 border-b border-warning/20">
      <AlertTriangle className="w-3.5 h-3.5 text-warning flex-shrink-0" />
      <p className="text-[11px] text-warning/80">
        <span className="font-semibold">Disclaimer:</span> Information only, not financial advice. All signals are generated by transparent rules — no guarantee of profit. You are solely responsible for your trading decisions.
      </p>
    </div>
  );
}
